@echo off
REM
REM SPDX-License-Identifier: BSD-2-Clause
REM
REM Copyright 2020 SUSE LLC
REM
REM Redistribution and use in source and binary forms, with or without
REM modification, are permitted provided that the following conditions
REM are met:
REM 1. Redistributions of source code must retain the above copyright
REM    notice, this list of conditions and the following disclaimer.
REM 2. Redistributions in binary form must reproduce the above copyright
REM    notice, this list of conditions and the following disclaimer in the
REM    documentation and/or other materials provided with the distribution.
REM
REM THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
REM IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
REM OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
REM IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
REM INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
REM NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
REM DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
REM THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
REM (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
REM THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
REM

set 386=
set AMD64=
set ATL_INC_PATH=
set ATL_INC_ROOT=
set ATL_LIB_PATH=
set BASEDIR=
set BUILD_ALLOW_COMPILER_WARNINGS=
set BUFFER_OVERFLOW_CHECKS=
set BUILD_ALT_DIR=
set BUILD_DEFAULT=
set BUILD_DEFAULT_TARGETS=
set BUILD_MAKE_PROGRAM=
set BUILD_MULTIPROCESSOR=
set BUILD_OPTIONS=
set COFFBASE_TXT_FILE=
set CPU=
set CRT_INC_PATH=
set CRT_LIB_PATH=
set DDKBUILDENV=
set DDK_INC_PATH=
set DDK_LIB_DEST=
set DDK_LIB_PATH=
set DDK_TARGET_OS=
set DEPRECATE_DDK_FUNCTIONS=
set DRIVER_INC_PATH=
set HALKIT_INC_PATH=
set HALKIT_LIB_PATH=
set IFSKIT_INC_PATH=
set IFSKIT_LIB_DEST=
set IFSKIT_LIB_PATH=
set Include=
set KMDF_INC_PATH=
set KMDF_LIB_PATH=
set LANGUAGE_NEUTRAL=
set Lib=
set LINK_LIB_IGNORE=
set MFC_INC_PATH=
set MFC_LIB_PATH=
set NEW_CRTS=
set MSC_OPTIMIZATION=
set NO_BINPLACE=
set NO_BROWSER_FILE=
set NTDBGFILES=
set NTDEBUG=
set NTDEBUGTYPE=
set NTMAKEENV=
set OAK_INC_PATH=
set PROJECT_ROOT=
set PUBLIC_ROOT=
set PUBLISH_CMD=
set RAZZLETOOLPATH=
set RCNOFONTMAP=
set SDK_INC_PATH=
set SDK_LIB_DEST=
set SDK_LIB_PATH=
set SDV=
set separate_object_root=
set UMDF_INC_PATH=
set USERNAME=kallan
set USE_OBJECT_ROOT=
set WDM_INC_PATH=
set WPP_CONFIG_PATH=
set _AMD64bit=
set _BUILDARCH=
set _BuildType=
set _NTDRIVE=
set _NTROOT=
set _NT_TARGET_VERSION=
set _RunOacr=
